name: Build libxml2 NuGet Package

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    env:
      VCPKG_ROOT: ${{ github.workspace }}\vcpkg

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup NuGet
        uses: NuGet/setup-nuget@v1

      - name: Install vcpkg
        run: |
          git clone https://github.com/microsoft/vcpkg.git
          git -C vcpkg pull
          .\vcpkg\bootstrap-vcpkg.bat
          .\vcpkg\vcpkg.exe integrate install

      - name: Install libxml2 with vcpkg
        run: .\vcpkg\vcpkg.exe install --triplet x64-windows

      - name: Pack NuGet package
        run: |
          nuget pack libxml2.nuspec -OutputDirectory out

      - name: Upload NuGet artifact
        uses: actions/upload-artifact@v4
        with:
          name: libxml2-nupkg
          path: out\*.nupkg
